:sectnums:
:sectanchors:
:toc: left
:toclevels: 2
:toc-title: Innhold
:icons: font

= Applikasjoner

== State of the union

Delt i oversikten på https://navikt.github.io/team-org/#_state_of_the_union

=== Repo og CI
Er appen på github? Er github actions i orden?

****
icon:check[role=green] Kode og build på GitHub +
icon:exclamation[role=yellow] Må flyttes til team org namespace +
icon:exclamation[role=yellow] Flytte TryggNok-proxy inn i monorepo? +
****


=== SW avhengigheter
Legg inn bruk av rammeverk, biblioteker osv som vi i teamet ikke standardiserer videre på?

****
icon:check[role=green] Java 17, Spring 2.7.3, node 16, ts target = esnext, react 18.2
****

=== Plattform
Mangler rundt riktig bruk av nais plattform. Veien ut til GCP, secret management, zero trust

****
icon:exclamation[role=yellow] Flytte til GCP
****

=== Lokalutvikling
Mangler rundt Lokalutvikling

****
icon:check[role=green] OK
****

=== Tjenester
Uønskede avhengigheter til ABAC, OPENAM, legacy systemer, MQ, eller konsumenter som bruker oss feil: usikrede APIer, SOAP, ...

****
icon:check[role=green] OK
****

=== Persistering
Databaser og køer. Problematikk rundt dette legges inn her

****
icon:exclamation[role=yellow] Postgres onprem +
icon:exclamation[role=yellow] Postgres kan oppgraderes +
****

=== Overvåkning
Logger, metrikker og alerts. Problematikk rundt manglende oversikt settes inn her

****
icon:exclamation[role=yellow] Logging, alerts, metrikker og monitorering må gås igjennom og dokumenteres
****

=== Sikkerhet
Legg inn mangler rundt dependency checking som snyk, dependabot, bruk av usikre biblioteker eller teknikker

****
icon:exclamation[role=yellow] Trenger gjennomgang +
icon:exclamation[role=yellow] Oppsett og oppfølging av dependabot/Snyk +
****

== Rammeverk og Versjoner

back-end::
* Java 17
* Spring Boot - 2.7.3
* Azure AD
* OnPrem Postgresql 11   (13 er default på GCP nå, 14 er også ute)
* Kafka (OnPrem v 2.3)
front-end::
* node 16

=== Node modules versioner

  npx npm-check-updates

.Frackend - per 25.08.2022
----
FULLT OPPGRADERT
----

.Frontend - per 25.08.2022
----
FULLT OPPGRADERT
----

=== Maven depenency versioner

  mvn versions:display-property-updates

.per 25.08.2022
----
The following version properties are referencing the newest available version:
  ${avro.version} .............................................. 1.11.0
  ${commons-collections4.version} ................................. 4.4
  ${commons-compress.version} .................................... 1.21
  ${commons-io.version} ........................................ 2.11.0
  ${confluent.version} .......................................... 7.2.1
  ${graphql-codegen.version} .................................... 5.4.1
  ${guava.version} ........................................... 31.1-jre
  ${hibernate-types-55.version} ................................ 2.18.0
  ${jetbrains.annotation.version} .............................. 23.0.0
  ${jna.version} ............................................... 5.12.1
  ${logstash-logback-encoder.version} ............................. 7.2
  ${lucene.version} ............................................ 8.11.2
  ${maven.dependency.plugin-version} ............................ 3.3.0
  ${microsoft-graph.version} ................................... 5.33.0
  ${msal4j.version} ............................................ 1.13.0
  ${nav-vault-jdbc.version} ..................................... 1.3.9
  ${postgresql.version} ........................................ 42.5.0
  ${scala.version} ............................................. 2.13.8
  ${shedlock.version} .......................................... 4.41.0
  ${simpleclient.version} ...................................... 0.16.0
  ${springdoc-openapi-ui.version} .............................. 1.6.11
  ${stax2-api.version} .......................................... 4.2.1
  ${testcontainers.version} .................................... 1.17.3
  ${wiremock.version} .......................................... 2.27.2
  ${xmlgraphics-commons.version} .................................. 2.7

The following version property updates are available:
  ${docx4j.version} .................................. 11.3.2 -> 11.4.7
----

[NOTE]
====
docx4j -> Nyere versjoner 11.4.x feiler med JAXB? Har ikke resolvet dette. Pretty sure dette kan løses ved spring boot 3 som kommer nov 2022

====

=== Dependabot
Prosjektet er også satt opp med github dependabot. Denne lager automatisker PR'er til repoet for å utføre oppdateringer. +
https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates +

WARNING: Disse følges ikke opp per i dag

== Backend

// TODO

== Frackend

// TODO

== Frontend

// TODO

=== Lokal utvikling mot miljø

// TODO