:sectnums:
:sectanchors:
:toc: left
:toclevels: 2
:toc-title: Innhold
:icons: font

= Applikasjoner

== State of the union

Delt i oversikten på https://navikt.github.io/team-org/#_state_of_the_union

=== Repo og CI
Er appen på github? Er github actions i orden?

****
icon:check[role=green] Kode og build på GitHub +
icon:exclamation[role=yellow] Må flyttes til team org namespace +
icon:exclamation[role=yellow] Flytte TryggNok-proxy inn i monorepo? +
****


=== SW avhengigheter
Legg inn bruk av rammeverk, biblioteker osv som vi i teamet ikke standardiserer videre på?

****
icon:exclamation[role=yellow] Gammel Spring versjon (2.5 -> 2.6)
****

=== Plattform
Mangler rundt riktig bruk av nais plattform. Veien ut til GCP, secret management, zero trust

****
icon:exclamation[role=yellow] Flytte til GCP
****

=== Lokalutvikling
Mangler rundt Lokalutvikling

****
icon:check[role=green] OK
****

=== Tjenester
Uønskede avhengigheter til ABAC, OPENAM, legacy systemer, MQ, eller konsumenter som bruker oss feil: usikrede APIer, SOAP, ...

****
icon:check[role=green] OK
****

=== Persistering
Databaser og køer. Problematikk rundt dette legges inn her

****
icon:exclamation[role=yellow] Postgres onprem +
icon:exclamation[role=yellow] Postgres kan oppgraderes +
****

=== Overvåkning
Logger, metrikker og alerts. Problematikk rundt manglende oversikt settes inn her

****
icon:exclamation[role=yellow] Logging, alerts, metrikker og monitorering må gås igjennom og dokumenteres
****

=== Sikkerhet
Legg inn mangler rundt dependency checking som snyk, dependabot, bruk av usikre biblioteker eller teknikker

****
icon:exclamation[role=yellow] Trenger gjennomgang +
icon:exclamation[role=yellow] Oppsett og oppfølging av dependabot/Snyk +
****

== Rammeverk og Versjoner

back-end::
* Java 16
* Azure AD
* OnPrem Postgresql 11   (13 er default på GCP nå, 14 er også ute)
* Kafka
front-end::
* node 16 (unsupported)

=== Node modules versioner

  npm outdated

.Frackend - per 15.08.2022
----
Package   Current  Wanted  Latest
axios      0.25.0  0.25.0  0.27.2
dotenv     14.3.2  14.3.2  16.0.1
passport    0.5.3   0.5.3   0.6.0
----

.Frontend - per 15.08.2022
----
Package                                   Current   Wanted   Latest
@apollo/client                              3.6.0    3.6.9    3.6.9
@emotion/css                               11.9.0  11.10.0  11.10.0
@fortawesome/fontawesome-common-types       6.1.1    6.1.2    6.1.2
@fortawesome/fontawesome-svg-core           6.1.1    6.1.2    6.1.2
@fortawesome/free-brands-svg-icons          6.1.1    6.1.2    6.1.2
@fortawesome/free-regular-svg-icons         6.1.1    6.1.2    6.1.2
@fortawesome/free-solid-svg-icons           6.1.1    6.1.2    6.1.2
@fortawesome/react-fontawesome             0.1.18   0.1.19    0.2.0
@graphql-codegen/cli                        2.6.2   2.11.6   2.11.6
@graphql-codegen/introspection              2.1.1    2.2.1    2.2.1
@graphql-codegen/typescript                 2.4.8    2.7.3    2.7.3
@graphql-codegen/typescript-operations      2.3.5    2.5.3    2.5.3
@graphql-codegen/typescript-react-apollo   3.2.11    3.3.3    3.3.3
@graphql-codegen/typescript-resolvers       2.6.1    2.7.3    2.7.3
@nivo/core                                 0.73.0   0.73.0   0.79.0
@nivo/line                                 0.73.0   0.73.0   0.79.1
@nivo/treemap                              0.73.0   0.73.0   0.79.1
@testing-library/jest-dom                  5.16.4   5.16.5   5.16.5
@testing-library/react                     13.1.1   13.3.0   13.3.0
@testing-library/user-event                14.1.1   14.4.3   14.4.3
@types/amplitude-js                        8.16.0   8.16.2   8.16.2
@types/jest                                27.4.1   27.5.2   28.1.6
@types/node                               17.0.29  17.0.45   18.7.3
@types/react                               18.0.8  18.0.17  18.0.17
@types/react-dom                           18.0.2   18.0.6   18.0.6
@types/yup                                0.29.13  0.29.14  0.29.14
amplitude-js                               8.18.1   8.19.0   8.19.0
baseui                                     11.0.1   11.2.1   12.0.0
core-js                                    3.22.3   3.24.1   3.24.1
graphql                                    16.4.0   16.5.0   16.5.0
moment                                     2.29.3   2.29.4   2.29.4
react                                      18.1.0   18.1.0   18.2.0
react-dom                                  18.1.0   18.2.0   18.2.0
react-json-tree                            0.16.2   0.16.2   0.17.0
react-router-dom                            5.3.1    5.3.3    6.3.0
styletron-engine-atomic                     1.4.8    1.5.0    1.5.0
styletron-react                             6.0.2    6.1.0    6.1.0
typescript                                  4.6.3    4.7.4    4.7.4
----

=== Maven depenency versioner

  mvn versions:display-property-updates

.per 15.08.2022
----
The following version properties are referencing the newest available version:
  ${commons-collections4.version} ................................. 4.4
  ${commons-compress.version} .................................... 1.21
  ${commons-io.version} ........................................ 2.11.0
  ${graphql-codegen.version} .................................... 5.4.0
  ${jetbrains.annotation.version} .............................. 23.0.0
  ${lombok.version} ........................................... 1.18.24
  ${maven.dependency.plugin-version} ............................ 3.3.0
  ${nav-vault-jdbc.version} ..................................... 1.3.9
  ${stax2-api.version} .......................................... 4.2.1
  ${wiremock.version} .......................................... 2.27.2

The following version property updates are available:
  ${avro.version} .................................... 1.10.2 -> 1.11.0
  ${confluent.version} ................................. 6.2.0 -> 7.2.1
  ${docx4j.version} .................................. 11.2.9 -> 11.4.7
  ${guava.version} ............................. 30.1.1-jre -> 31.1-jre
  ${hibernate-types-52.version} ...................... 2.16.1 -> 2.17.3
  ${jna.version} ..................................... 5.11.0 -> 5.12.1
  ${logstash-logback-encoder.version} ...................... 6.6 -> 7.2
  ${lucene.version} ................................... 8.9.0 -> 8.11.2
  ${microsoft-graph.version} ......................... 5.21.0 -> 5.31.0
  ${msal4j.version} .................................. 1.11.3 -> 1.13.0
  ${scala.version} ................................... 2.13.6 -> 2.13.8
  ${shedlock.version} ................................ 4.26.0 -> 4.40.0
  ${simpleclient.version} ............................ 0.15.0 -> 0.16.0
  ${springdoc-openapi-ui.version} ...................... 1.6.8 -> 1.6.9
  ${testcontainers.version} .......................... 1.17.1 -> 1.17.3
----

=== Dependabot
Prosjektet er også satt opp med github dependabot. Denne lager automatisker PR'er til repoet for å utføre oppdateringer. +
https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates +

WARNING: Disse følges ikke opp per i dag

== Backend

// TODO

== Frackend

// TODO

== Frontend

// TODO

=== Lokal utvikling mot miljø

// TODO