apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: team-catalog-backend-alerts
  namespace: org
  labels:
    team: org
spec:
  groups:
    - name: team-catalog-backend_down
      rules:
        - alert: team-catalog-backend pod nede
          expr: kube_deployment_status_replicas_unavailable{deployment="team-catalog-backend"} > 0
          for: 3m
          annotations:
            action: "`kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }} -c {{ $labels.app }}` for logger"
            summary: "{{ $labels.app }} er nede"
          labels:
            namespace: nom
            severity: critical
    - name: team-catalog-backend_high_failrate
      rules:
        - alert: team-catalog-backend høy feilrate i logger
          expr: (sum(loki:service:loglevel:count1m{service_name="team-catalog-backend", detected_level="error"}) / sum(loki:service:loglevel:count1m{service_name="team-catalog-backend"})) > 0.05
          for: 3m
          annotations:
            summary: "{{ $labels.service_name }} har {{ $value | humanizePercentage }} feilmeldinger i loggene i løpet av de siste 3 minuttene."
          labels:
            namespace: nom
            severity: warning