apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: team-catalog-backend
  namespace: org
  labels:
    team: org
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: eb3dd903-42c9-4337-b8df-618a45da47cd
      replyURLs:
        - https://teamkatalog-api.intern.nav.no/oauth2/callback
        - https://teamkatalog.nav.no/oauth2/callback
        - https://teamkatalog.intern.nav.no/oauth2/callback
        - https://teamkatalogen.nav.no/oauth2/callback
        - https://teamkatalogen.intern.nav.no/oauth2/callback
  accessPolicy:
    inbound:
      rules:
        - application: team-catalog-frackend
          namespace: org
          cluster: prod-gcp
        - application: nom-ui2
          namespace: org
          cluster: prod-gcp
        - application: org-token-tool
          namespace: org
          cluster: prod-gcp
        - application: behandlingskatalog-backend
          namespace: teamdatajegerne
          cluster: prod-gcp
        - application: etterlevelse-backend
          namespace: teamdatajegerne
          cluster: prod-gcp
        - application: tryggnok-proxy
          namespace: org
          cluster: prod-gcp
        - application: nada-backend
          namespace: nada
          cluster: prod-gcp
        - application: nada-update-po-teams-dataset
          namespace: nada
          cluster: prod-gcp
        - application: security-champion-slackbot
          namespace: security-champion-admin
          cluster: prod-gcp
        - application: portal
          namespace: navdig
          cluster: prod-gcp
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp
        - application: shout-out-sync-service
          namespace: shout-out
          cluster: prod-gcp
        - application: appsec-stats
          namespace: appsec
          cluster: prod-gcp
    outbound:
      rules:
        - application: nom-api
          namespace: nom
          cluster: prod-gcp
      external:
        - host: slack.com
        - host: console.nav.cloud.nais.io
        - host: behandlingskatalog-backend.intern.nav.no

  ingresses:
    - https://teamkatalog-api.intern.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  resources:
    limits:
      memory: 2500Mi
    requests:
      cpu: 75m
      memory: 2000Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: teamcat-enckey
    - secret: teamcat-mail-pwd
    - secret: teamcat-slack-token
    - secret: teamcat-nais-console-token
    - secret: teamcat-srvteamcat
  env:
    - name: TEAM_CATALOG_ENVLEVEL
      value: primary
    - name: ENVIRONMENT_CLASS
      value: prod
    - name: DEFAULT_PRODUCTAREA_UUID
      value: "eeb5dc96-3a6f-4d21-9248-2cb7acedd57b"
    - name: TEAM_CATALOG_SECURITY_REDIRECT_URIS
      value: "https://teamkatalog.nav.no,https://teamkatalog.intern.nav.no"
    - name: CLIENT_PROCESS_CAT_BASE_URL
      value: "https://behandlingskatalog-backend.intern.nav.no"
    - name: CLIENT_NOM_GRAPHQL_URL
      value: "http://nom-api.nom.svc.cluster.local/graphql"
    - name: AZURE_CLIENT_GROUPS_ADMIN
      value: "eb3dd903-42c9-4337-b8df-618a45da47cd"
    - name: AZURE_APP_MAIL_USER
      value: "teamkatalog@nav.no"
    - name: JDK_JAVA_OPTIONS
      value: "-Xmx1536m -Xms1024m -XX:+UseParallelGC -XX:ActiveProcessorCount=4"
    - name: OTEL_JAVAAGENT_LOGGING  # Bli kvitt Otel loggingen https://opentelemetry.io/docs/zero-code/java/agent/configuration/#java-agent-logging-output
      value: none
  gcp:
    sqlInstances:
      - name: team-catalog-v2
        type: POSTGRES_16
        tier: db-custom-1-3840
        databases:
          - name: team-catalog
            envVarPrefix: BACKEND_DB
