apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{name}}
  namespace: nom
  labels:
    team: nom
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: {{adminGroup}}
      replyURLs:
      {{#each replies as |url|}}
         - {{url}}
      {{/each}}
  accessPolicy:
    inbound:
      rules:
        {{#each accessPolicy.inbound.rules}}
            - application: {{this.application}}
              namespace: {{this.namespace}}
              cluster: {{this.cluster}}
        {{/each}}
    outbound:
      rules:
        {{#each accessPolicy.outbound.rules}}
           - application: {{this.application}}
             namespace: {{this.namespace}}
             cluster: {{this.cluster}}
        {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/srv
        kvPath: {{vaultSrvPath}}
  prometheus:
    enabled: true
    path: internal/metrics
  webproxy: true
  envFrom:
    - secret: teamcat-enckey
    - secret: teamcat-mail-pwd
    - secret: teamcat-slack-token
  env:
  {{#each env}}
      - name: {{this.name}}
        value: {{this.value}}
  {{/each}}
