apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: team-catalog-backend
  namespace: org
  labels:
    team: org
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: eedc0f72-585e-4814-94f4-25b43d9c8d1b
      replyURLs:
        - https://teamkatalog-api.intern.dev.nav.no/oauth2/callback
        - https://teamkatalog.ekstern.dev.nav.no/oauth2/callback
        - https://teamkatalogen.ekstern.dev.nav.no/oauth2/callback
        - http://localhost:8080/oauth2/callback
        - http://localhost:3000/oauth2/callback
  accessPolicy:
    inbound:
      rules:
        - application: team-catalog-frackend
          namespace: org
          cluster: dev-gcp
        - application: nom-ui2
          namespace: org
          cluster: dev-gcp
        - application: org-token-tool
          namespace: org
          cluster: dev-gcp
        - application: behandlingskatalog-backend
          namespace: teamdatajegerne
          cluster: dev-gcp
        - application: tryggnok-proxy
          namespace: org
          cluster: dev-gcp
        - application: nada-backend
          namespace: nada
          cluster: dev-gcp
        - application: security-champion-slackbot
          namespace: security-champion-admin
          cluster: dev-gcp
        - application: portal
          namespace: navdig
          cluster: dev-gcp
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
        - application: shout-out-sync-service
          namespace: shout-out
          cluster: dev-gcp
    outbound:
      rules:
        - application: nom-api
          namespace: nom
          cluster: dev-gcp
      external:
        - host: slack.com
        - host: console.nav.cloud.nais.io
        - host: behandlingskatalog-backend.intern.dev.nav.no

  ingresses:
    - https://teamkatalog-api.intern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      memory: 1024Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /internal/prometheus
  envFrom:
    - secret: teamcat-enckey
    - secret: teamcat-mail-pwd
    - secret: teamcat-slack-token
    - secret: teamcat-nais-console-token
    - secret: teamcat-srvteamcat
  env:
    - name: TEAM_CATALOG_ENVLEVEL
      value: primary
    - name: ENVIRONMENT_CLASS
      value: preprod
    - name: DEFAULT_PRODUCTAREA_UUID
      value: "c5557f01-35c1-43fa-a0b4-2c35c50a9905"
    - name: TEAM_CATALOG_SECURITY_REDIRECT_URIS
      value: "https://teamkatalog-api.intern.dev.nav.no,http://localhost:3000"
    - name: CLIENT_PROCESS_CAT_BASE_URL
      value: "https://behandlingskatalog-backend.intern.dev.nav.no"
    - name: CLIENT_NOM_GRAPHQL_URL
      value: "http://nom-api.nom.svc.cluster.local/graphql"
    - name: AZURE_CLIENT_GROUPS_ADMIN
      value: "eedc0f72-585e-4814-94f4-25b43d9c8d1b"
    - name: AZURE_APP_MAIL_USER
      value: "teamkatalog@nav.no"
    - name: DEV_EMAIL_ALLOW_LIST
      value: "andreas.skomedal@nav.no"

  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: team-catalog
            envVarPrefix: BACKEND_DB
