version: '3.7'
name: "team-catalog-backend"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5412:5432

  kafka:
    image: apache/kafka-native:latest
    ports:
      - 9092:9092

volumes:
  postgres:
