import {IStrings} from "./intl";

export const no: IStrings = {
  PRODUCT: "Tverrfaglige produktteam (TFPT)",
  PRODUCT_DESCRIPTION: "Tverrfaglige produktteam (TFPT) - Teamet eies enten av et produktområde eller av en linjeenhet. Besluttes i Utviklingsmøte eller i budsjettprosessen (porteføljeprosessen).",
  ADMINISTRATION: "Forvaltningsteam",
  ADMINISTRATION_DESCRIPTION: "Forvaltningsteam - Teamet eies av IT-avdelingen. Forvaltningsleverandør utfører størstedelen av forvaltning og videreutvikling.",
  IT: "IT-team",
  IT_DESCRIPTION: "IT-team - Teamet eies av IT-avdelingen. IT-avdelingen forvalter og videreutvikler med egne og innleide folk.",
  PROJECT: "Prosjektteam",
  PROJECT_DESCRIPTION: "Prosjektteam - Teamet tilhører et prosjekt.",
  OTHER: "Annet",
  OTHER_DESCRIPTION: "Andre team som ikke inngår i de andre kategoriene.",
  UNKNOWN: "Ukjent",
  UNKNOWN_DESCRIPTION: "Ukjent",
  edit: "Rediger",
  dataIsMissing: "Ikke fylt ut",

  PRODUCT_AREA_AREATYPE_DESCRIPTION: "Produktområde",
  PROJECT_AREATYPE_DESCRIPTION: "Prosjekt",
  IT_AREATYPE_DESCRIPTION: "IT-område",
  OTHER_AREATYPE_DESCRIPTION: "Annet",

  DEVELOPER: "Utvikler",
  TESTER: "Tester",
  LEAD: "Teamleder",
  TECH_LEAD: "Tech lead",
  TEST_LEAD: "Testleder",
  AGILE_COACH: "Agile coach",
  ARCHITECT: "Arkitekt",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  DESIGNER: "Designer",
  DOMAIN_EXPERT: "Domeneekspert",
  OPERATIONS: "Drift",
  DOMAIN_RESPONSIBLE: "Fagansvarlig",
  DOMAIN_RESOURCE: "Fagressurs",
  BUSINESS_ANALYST: "Forretningsutvikler",
  FUNCTIONAL_ADVISER: "Funksjonell rådgiver",
  SOLUTION_ARCHITECT: "Løsningsarkitekt",
  PRODUCT_OWNER: "Produkteier",
  PRODUCT_LEAD: "Produktleder",
  SECURITY_ARCHITECT: "Sikkerhetsarkitekt",
  TECHNICAL_ADVISER: "Teknisk rådgiver",
  TECHNICAL_TESTER: "Teknisk tester",
  MAINTENANCE_MANAGER: "Vedlikeholdsansvarlig",
  COMMUNICATION_ADVISER: "Kommunikasjonsrådgiver",
  AREA_LEAD: "Områdeleder",
  LEGAL_ADVISER: "Jurist",
  SECURITY_CHAMPION: "Security champion",
  PROFIT_COACH: "Gevinst coach",
  CONTROLLER: "Controller",
  UU_CHAMPION: "UU-Champion",

  INTERNAL: "Intern",
  EXTERNAL: "Ekstern",

  nonNavEmployee: "Ikke NAV",

  TEAM: "Team",
  AREA: "Område",

  Team: "team",
  ProductArea: "område",
  Cluster: "klynge",

  administrate: "Admin",
  CREATE: "Opprett",
  DELETE: "Slett",
  UPDATE: "Oppdater",
  action: "Aksjon",
  audit: "Versjonering",
  mailLog: "Mail log",
  auditNotFound: "Fant ingen versjonering",
  auditNr: "Versjon #",
  audits: "Versjoneringer",
  close: "Lukk",
  emptyTable: "Ingen",
  id: "Id",
  searchId: "S\xf8k etter id",
  lastChanges: "Siste endringer",
  prevButton: "Forrige",
  nextButton: "Neste",
  rows: "Rader",
  table: "Tabellnavn",
  time: "Tidspunkt",
  user: "Bruker",
  version: "Versjon",
  view: "Vis",
  settings: "Innstillinger",
  abort: "Avbryt",
  save: "Lagre",
  pageNotFound: "Oida 404! Fant ikke den siden der nei",
  teamNotFound: "Fant ikke teamet",
  productAreaNotFound: "Fant ikke området",
  clusterNotFound: "Fant ikke klynge",
  linkToAllTeamsText: "Gå til oversikt over alle team her",
  linkToAllProductAreasText: "Gå til oversikt over alle områder her",
};

export const en: IStrings = {
  PRODUCT: "Interdisciplinary Product Team (TFPT)",
  PRODUCT_DESCRIPTION: "Interdisciplinary Product Team (TFPT) - The team is owned either by a product area or by a line unit. Decided in the Development Meeting or in the budget process (portfolio process).",
  ADMINISTRATION: "Management team",
  ADMINISTRATION_DESCRIPTION: "Management team - The team is owned by the IT department. Management supplier performs most of the management and further development.",
  IT: "IT Team",
  IT_DESCRIPTION: "IT team - The team is owned by the IT department. The IT department manages and further develops with its own and hired people.",
  PROJECT: "Project team",
  PROJECT_DESCRIPTION: "Project team - The team belongs to a project.",
  OTHER: "Other teams",
  OTHER_DESCRIPTION: "Other teams not included in the other categories.",
  UNKNOWN: "Unknown",
  UNKNOWN_DESCRIPTION: "Unknown",
  edit: "Edit",
  dataIsMissing: "Data is missing",

  PRODUCT_AREA_AREATYPE_DESCRIPTION: "Product area",
  PROJECT_AREATYPE_DESCRIPTION: "Project",
  IT_AREATYPE_DESCRIPTION: "IT-Area",
  OTHER_AREATYPE_DESCRIPTION: "Other",

  LEAD: "Team lead",
  DEVELOPER: "Developer",
  TESTER: "Tester",
  TECH_LEAD: "Tech lead",
  TEST_LEAD: "Test lead",
  PRODUCT_OWNER: "Product owner",
  PRODUCT_LEAD: "Product lead",
  SECURITY_ARCHITECT: "Security architect",
  SOLUTION_ARCHITECT: "Solution architect",
  BUSINESS_ANALYST: "Business analyst",
  DOMAIN_EXPERT: "Domain expert",
  DOMAIN_RESPONSIBLE: "Domain responsible",
  DOMAIN_RESOURCE: "Domain resource",
  ARCHITECT: "Architect",
  AGILE_COACH: "Agile coach",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  MAINTENANCE_MANAGER: "Maintenance manager",
  DESIGNER: "Designer",
  OPERATIONS: "Operations",
  FUNCTIONAL_ADVISER: "Functional adviser",
  TECHNICAL_ADVISER: "Technical adviser",
  TECHNICAL_TESTER: "Technical tester",
  COMMUNICATION_ADVISER: "Communication adviser",
  AREA_LEAD: "Area lead",
  LEGAL_ADVISER: "Legal adviser",
  SECURITY_CHAMPION: "Security champion",
  UU_CHAMPION: "UU champion",
  PROFIT_COACH: "Profit coach",
  CONTROLLER: "Controller",

  INTERNAL: "Internal",
  EXTERNAL: "External",

  nonNavEmployee: "Not NAV",

  TEAM: "Team",
  AREA: "Area",

  Team: "team",
  ProductArea: "product area",
  Cluster: "cluster",

  administrate: "Admin",
  CREATE: "Create",
  DELETE: "Delete",
  UPDATE: "Update",
  action: "Action",
  audit: "Audit",
  mailLog: "Mail log",
  auditNotFound: "No audits found",
  auditNr: "Audit #",
  audits: "Audits",
  close: "Close",
  emptyTable: "No",
  id: "Id",
  searchId: "Search by id",
  lastChanges: "Last changes",
  prevButton: "Previous",
  nextButton: "Next",
  rows: "Rows",
  table: "Table name",
  time: "Time",
  user: "User",
  version: "Version",
  view: "View",
  settings: "Settings",
  abort: "Abort",
  save: "Save",
  pageNotFound: "Oops 404! Couldn't find that page",
  teamNotFound: "Could not find the team",
  productAreaNotFound: "Could not find the area",
  clusterNotFound: "Could not find the cluster",
  linkToAllTeamsText: "Go to all teams",
  linkToAllProductAreasText: "Go to all areas",
};
