import type { IStrings } from "./intl";

export const no: IStrings = {
  PRODUCT: "Tverrfaglige produktteam (TFPT)",
  PRODUCT_DESCRIPTION:
    "Tverrfaglige produktteam (TFPT) - Teamet eies enten av en seksjon eller av en linjeenhet. Besluttes i Utviklingsmøte eller i budsjettprosessen (porteføljeprosessen).",
  ADMINISTRATION: "Forvaltningsteam",
  ADMINISTRATION_DESCRIPTION:
    "Forvaltningsteam - Teamet eies av IT-avdelingen. Forvaltningsleverandør utfører størstedelen av forvaltning og videreutvikling.",
  IT: "IT-team",
  IT_DESCRIPTION:
    "IT-team - Teamet eies av IT-avdelingen. IT-avdelingen forvalter og videreutvikler med egne og innleide folk.",
  PROJECT: "Prosjektteam",
  PROJECT_DESCRIPTION: "Prosjektteam - Teamet tilhører et prosjekt.",
  OTHER: "Annet",
  OTHER_DESCRIPTION: "Annet - Dersom ingen av de øvrige verdiene passer",
  UNKNOWN: "Ukjent",
  UNKNOWN_DESCRIPTION: "Ukjent",
  edit: "Endre",
  dataIsMissing: "Ikke fylt ut",

  PRODUCT_AREA_AREATYPE_DESCRIPTION: "Seksjon",
  PROJECT_AREATYPE_DESCRIPTION: "Prosjekt",
  IT_AREATYPE_DESCRIPTION: "IT-område",
  OTHER_AREATYPE_DESCRIPTION: "Annet",

  AGILE_COACH: "Agile coach",
  ARCHITECT: "Arkitekt",
  AREA_LEAD: "Seksjonleder",
  BUSINESS_ANALYST: "Forretningsutvikler",
  COMMUNICATION_ADVISER: "Kommunikasjonsrådgiver",
  CONTROLLER: "Controller",
  DATA_ENGINEER: "Data engineer",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  DESIGNER: "Designer",
  DESIGN_LEAD: "Design lead",
  DESIGN_RESEARCHER: "Design researcher",
  DEVELOPER: "Utvikler",
  DOMAIN_EXPERT: "Domeneekspert",
  DOMAIN_RESOURCE: "Fagressurs",
  DOMAIN_RESPONSIBLE: "Fagansvarlig",
  FRONTEND: "Frontend",
  FUNCTIONAL_ADVISER: "Funksjonell rådgiver",
  HEAD_OF_LEGAL: "Juridisk ansvarlig",
  LEAD: "Teamleder",
  LEGAL_ADVISER: "Jurist",
  MAINTENANCE_MANAGER: "Vedlikeholdsansvarlig",
  OPERATIONS: "Drift",
  PLATFORM_SYSTEM_TECHNICIAN: "Platform system technician",
  PRINCIPAL: "Prinsipal",
  PRODUCT_LEAD: "Produktleder",
  PROFIT_COACH: "Gevinst coach",
  PROJECT_MANAGER: "Prosjektleder",
  SECURITY_ARCHITECT: "Sikkerhetsarkitekt",
  SECURITY_CHAMPION: "Security champion",
  SOLUTION_ARCHITECT: "Løsningsarkitekt",
  STAFFING_MANAGER: "Bemanningsansvarlig",
  STRATEGIC_PRODUCT_LEAD: "Product lead",
  SUBJECT_MATTER_EXPERT: "Fagekspert",
  TEAMCOACH: "Teamcoach",
  TECH_DOMAIN_SPECIALIST: "Teknisk domenespesialist",
  TECH_LEAD: "Tech lead",
  TECHNICAL_ADVISER: "Teknisk rådgiver",
  TECHNICAL_TESTER: "Teknisk tester",
  TECHNOLOGY_LEAD: "Teknologileder",
  TESTER: "Tester",
  TEST_LEAD: "Testleder",
  UU_CHAMPION: "UU-Champion",
  UU_SPECIALIST: "UU-spesialist",
  VISUAL_ANALYTICS_ENGINEER: "Visual Analytics Engineer",
  WEB_ANALYST: "Webanalytiker",

  // leader group roles
  LEADER: "Leder",
  DISCIPLINE_DIRECTOR: "Fagdirektør",
  PERSONELLROSTER_RESPONSIBLE: "Personal og bemanningsansvarlig",
  DISCIPLINE_AND_DELIVERY_MANAGER: "Fag og leveranseleder",

  STREAM_ALIGNED: "Verdistrømteam",
  STREAM_ALIGNED_DESCRIPTION:
    "Verdistrømteam - Håndterer flyten av alle endringer innenfor sin egen verdistrøm. Verdistrømmen kan for eksempel gjelde for hele eller deler av et produkt. Dette er den primære team-typen.",
  ENABLING: "Tilretteleggingsteam",
  ENABLING_DESCRIPTION:
    "Tilretteleggingsteam - Bistår øvrige team med å fjerne hindringer, samt skaffe nye kapabiliteter og kunnskap.",
  PLATFORM: "Plattformteam",
  PLATFORM_DESCRIPTION:
    "Plattformteam - Tilbyr interne tjenester, pakket inn som et internt produkt, som øvrige team avhenger av for å akselerere leveransetakten.",
  COMPLICATED_SUBSYSTEM: "Subsystemteam",
  COMPLICATED_SUBSYSTEM_DESCRIPTION:
    "Subsystemteam - Der hvor betydelig og lite tilgjengelig spisskompetanse er nødvendig. Skjermer øvrige team for kompleksitet gjennom å tilby en komplisert del av systemet som en tjeneste.",
  WORKGROUP: "Arbeidsgruppe",
  WORKGROUP_DESCRIPTION:
    "Arbeidsgruppe - Gruppe som møtes sporadisk, uten at medlemmene tilbringer majoriteten av tiden sin der. Prosjektteam, med definert start og sluttdato, er også en arbeidsgruppe.",
  MANAGEMENT: "Ledergruppe",
  MANAGEMENT_DESCRIPTION:
    "Ledergruppe - En gruppe ledere som fungerer som team, men som har en mer administrativ rolle enn øvrige team-typer.",
  PROJECTGROUP: "Prosjektgruppe",
  PROJECTGROUP_DESCRIPTION: "Prosjektgruppe",

  INTERNAL: "Intern",
  EXTERNAL: "Ekstern",

  nonNavEmployee: "Ikke NAV",

  TEAM: "Team",
  AREA: "Seksjon",

  Team: "team",
  ProductArea: "seksjon",
  Cluster: "klynge",

  administrate: "Admin",
  CREATE: "Opprett",
  DELETE: "Slett",
  UPDATE: "Oppdater",
  action: "Aksjon",
  audit: "Versjonering",
  mailLog: "Mail log",
  auditNotFound: "Fant ingen versjonering",
  auditNr: "Versjon #",
  audits: "Versjoneringer",
  close: "Lukk",
  emptyTable: "Ingen",
  id: "Id",
  searchId: "S\u00F8k etter id",
  lastChanges: "Siste endringer",
  prevButton: "Forrige",
  nextButton: "Neste",
  rows: "Rader",
  table: "Tabellnavn",
  time: "Tidspunkt",
  user: "Bruker",
  version: "Versjon",
  view: "Vis",
  settings: "Innstillinger",
  abort: "Avbryt",
  save: "Lagre",
  pageNotFound: "Oida 404! Fant ikke den siden der nei",
  teamNotFound: "Fant ikke teamet",
  productAreaNotFound: "Fant ikke seksjonen",
  clusterNotFound: "Fant ikke klynge",
  linkToAllTeamsText: "Gå til oversikt over alle team her",
  linkToAllProductAreasText: "Gå til oversikt over alle seksjoner her",
  ACTIVE: "Aktiv",
  PLANNED: "Fremtidig",
  INACTIVE: "Avviklet",
};

export const en: IStrings = {
  PRODUCT: "Interdisciplinary Product Team (TFPT)",
  PRODUCT_DESCRIPTION:
    "Interdisciplinary Product Team (TFPT) - The team is owned either by a section or by a line unit. Decided in the Development Meeting or in the budget process (portfolio process).",
  ADMINISTRATION: "Management team",
  ADMINISTRATION_DESCRIPTION:
    "Management team - The team is owned by the IT department. Management supplier performs most of the management and further development.",
  IT: "IT Team",
  IT_DESCRIPTION:
    "IT team - The team is owned by the IT department. The IT department manages and further develops with its own and hired people.",
  PROJECT: "Project team",
  PROJECT_DESCRIPTION: "Project team - The team belongs to a project.",
  OTHER: "Other teams",
  OTHER_DESCRIPTION: "If none of the values above is correct",
  UNKNOWN: "Unknown",
  UNKNOWN_DESCRIPTION: "Unknown",
  edit: "Edit",
  dataIsMissing: "Data is missing",

  PRODUCT_AREA_AREATYPE_DESCRIPTION: "Section",
  PROJECT_AREATYPE_DESCRIPTION: "Project",
  IT_AREATYPE_DESCRIPTION: "IT-Area",
  OTHER_AREATYPE_DESCRIPTION: "Other",

  AGILE_COACH: "Agile coach",
  ARCHITECT: "Architect",
  AREA_LEAD: "Area lead",
  BUSINESS_ANALYST: "Business analyst",
  COMMUNICATION_ADVISER: "Communication adviser",
  CONTROLLER: "Controller",
  DATA_ENGINEER: "Data engineer",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  DESIGNER: "Designer",
  DESIGN_LEAD: "Design lead",
  DESIGN_RESEARCHER: "Design researcher",
  DEVELOPER: "Developer",
  DOMAIN_EXPERT: "Domain expert",
  DOMAIN_RESOURCE: "Domain resource",
  DOMAIN_RESPONSIBLE: "Domain responsible",
  FRONTEND: "Frontend",
  FUNCTIONAL_ADVISER: "Functional adviser",
  HEAD_OF_LEGAL: "Head of legal",
  LEAD: "Team lead",
  LEGAL_ADVISER: "Legal adviser",
  MAINTENANCE_MANAGER: "Maintenance manager",
  OPERATIONS: "Operations",
  PLATFORM_SYSTEM_TECHNICIAN: "Platform system technician",
  PRINCIPAL: "Principal",
  PRODUCT_LEAD: "Product lead",
  PROFIT_COACH: "Profit coach",
  PROJECT_MANAGER: "Project manager",
  SECURITY_ARCHITECT: "Security architect",
  SECURITY_CHAMPION: "Security champion",
  SOLUTION_ARCHITECT: "Solution architect",
  STAFFING_MANAGER: "Staffing manager",
  STRATEGIC_PRODUCT_LEAD: "Product lead",
  SUBJECT_MATTER_EXPERT: "Subject matter expert",
  TEAMCOACH: "Teamcoach",
  TECH_DOMAIN_SPECIALIST: "Tech domain specialist",
  TECH_LEAD: "Tech lead",
  TECHNICAL_ADVISER: "Technical adviser",
  TECHNICAL_TESTER: "Technical tester",
  TECHNOLOGY_LEAD: "Teknologileder",
  TESTER: "Tester",
  TEST_LEAD: "Test lead",
  UU_CHAMPION: "UU champion",
  UU_SPECIALIST: "UU-specialist",
  VISUAL_ANALYTICS_ENGINEER: "Visual Analytics Engineer",
  WEB_ANALYST: "Web analyst",

  // leader group roles
  LEADER: "Leader",
  DISCIPLINE_DIRECTOR: "Discipline director",
  PERSONELLROSTER_RESPONSIBLE: "Personell roster responsible",
  DISCIPLINE_AND_DELIVERY_MANAGER: "Discipline and delivery manager",

  STREAM_ALIGNED: "Stream aligned",
  STREAM_ALIGNED_DESCRIPTION:
    "Stream aligned - Manages the flow of all changes within its own value stream. The value stream can, for example, apply to all or parts of a product. This is the primary team type.",
  ENABLING: "Enabling",
  ENABLING_DESCRIPTION:
    "Enabling - Assists other teams in removing obstacles, as well as acquiring new capabilities and knowledge.",
  PLATFORM: "Platform",
  PLATFORM_DESCRIPTION:
    "Platform - Provides internal services, packaged as an internal product, that other teams depend on to accelerate the pace of delivery.",
  COMPLICATED_SUBSYSTEM: "Complicated subsystem",
  COMPLICATED_SUBSYSTEM_DESCRIPTION:
    "Complicated subsystem - Where significant and scarcely available specialist expertise is required. Screens other teams for complexity by offering a complicated part of the system as a service.",
  WORKGROUP: "Workgroup",
  WORKGROUP_DESCRIPTION:
    "Workgroup - Group that meets sporadically, without the members spending the majority of their time there. Project teams, with a defined start and end date, are also a working group.",
  MANAGEMENT: "Management",
  MANAGEMENT_DESCRIPTION:
    "Management - A group of managers who function as a team, but who have a more administrative role than other team types.",
  PROJECTGROUP: "Projectgroup",
  PROJECTGROUP_DESCRIPTION: "Projectgroup",

  INTERNAL: "Internal",
  EXTERNAL: "External",

  nonNavEmployee: "Not NAV",

  TEAM: "Team",
  AREA: "Area",

  Team: "team",
  ProductArea: "product area",
  Cluster: "cluster",

  administrate: "Admin",
  CREATE: "Create",
  DELETE: "Delete",
  UPDATE: "Update",
  action: "Action",
  audit: "Audit",
  mailLog: "Mail log",
  auditNotFound: "No audits found",
  auditNr: "Audit #",
  audits: "Audits",
  close: "Close",
  emptyTable: "No",
  id: "Id",
  searchId: "Search by id",
  lastChanges: "Last changes",
  prevButton: "Previous",
  nextButton: "Next",
  rows: "Rows",
  table: "Table name",
  time: "Time",
  user: "User",
  version: "Version",
  view: "View",
  settings: "Settings",
  abort: "Abort",
  save: "Save",
  pageNotFound: "Oops 404! Couldn't find that page",
  teamNotFound: "Could not find the team",
  productAreaNotFound: "Could not find the area",
  clusterNotFound: "Could not find the cluster",
  linkToAllTeamsText: "Go to all teams",
  linkToAllProductAreasText: "Go to all areas",
  ACTIVE: "Active",
  PLANNED: "Planned",
  INACTIVE: "Inactive",
};
