import { IStrings } from "./intl";

export const no: IStrings = {
  PRODUCT: "Produktteam",
  ADMINISTRATION: "Forvaltningsteam",
  IT: "IT-team",
  PROJECT: "Prosjektteam",
  OTHER: "Annet",
  UNKNOWN: "Ukjent",
  edit: "Rediger",
  dataIsMissing: "Ikke fylt ut",

  DEVELOPER: "Utvikler",
  TESTER: "Tester",
  LEAD: "Teamleder",
  TECH_LEAD: "Tech lead",
  TEST_LEAD: "Testleder",
  AGILE_COACH: "Agile coach",
  ARCHITECT: "Arkitekt",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  DESIGNER: "Designer",
  DOMAIN_EXPERT: "Domeneekspert",
  OPERATIONS: "Drift",
  DOMAIN_RESPONSIBLE: "Fagansvarlig",
  DOMAIN_RESOURCE: "Fagressurs",
  BUSINESS_ANALYST: "Forretningsutvikler",
  FUNCTIONAL_ADVISER: "Funksjonell rådgiver",
  SOLUTION_ARCHITECT: "Løsningsarkitekt",
  PRODUCT_OWNER: "Produkteier",
  SECURITY_ARCHITECT: "Sikkerhetsarkitekt",
  TECHNICAL_ADVISER: "Teknisk rådgiver",
  TECHNICAL_TESTER: "Teknisk tester",
  MAINTENANCE_MANAGER: "Vedlikeholdsansvarlig",

  INTERNAL: "Intern",
  EXTERNAL: "Ekstern",

  administrate: "Admin",
  CREATE: "Opprett",
  DELETE: "Slett",
  UPDATE: "Oppdater",
  action: "Aksjon",
  audit: "Versjonering",
  auditNotFound: "Fant ingen versjonering",
  auditNr: "Versjon #",
  audits: "Versjoneringer",
  close: "Lukk",
  emptyTable: "Ingen",
  id: "Id",
  searchId: "S\xf8k etter id",
  lastChanges: "Siste endringer",
  prevButton: "Forrige",
  nextButton: "Neste",
  rows: "Rader",
  table: "Tabellnavn",
  time: "Tidspunkt",
  user: "Bruker",
  version: "Versjon",
  view: "Vis",
  settings: "Innstillinger",
  abort: "Avbryt",
  save: "Lagre",
  pageNotFound: "Oida 404! Fant ikke den siden der nei",
  teamNotFound: "Fant ikke teamet",
  producatAreaNotFound: "Fant ikke området",
  linkToAllTeamsText: "Gå til oversikt over alle teams her",
  linkToAllProductAreasText: "Gå til oversikt over alle områder her",
};

export const en: IStrings = {
  PRODUCT: "Product",
  ADMINISTRATION: "Administration",
  IT: "IT",
  PROJECT: "Project",
  OTHER: "Other",
  UNKNOWN: "Unknown",
  edit: "Edit",
  dataIsMissing: "Data is missing",

  LEAD: "Team lead",
  DEVELOPER: "Developer",
  TESTER: "Tester",
  TECH_LEAD: "Tech lead",
  TEST_LEAD: "Test lead",
  PRODUCT_OWNER: "Product owner",
  SECURITY_ARCHITECT: "Security architect",
  SOLUTION_ARCHITECT: "Solution architect",
  BUSINESS_ANALYST: "Business analyst",
  DOMAIN_EXPERT: "Domain expert",
  DOMAIN_RESPONSIBLE: "Domain responsible",
  DOMAIN_RESOURCE: "Domain resource",
  ARCHITECT: "Architect",
  AGILE_COACH: "Agile coach",
  DATA_MANAGER: "Data manager",
  DATA_SCIENTIST: "Data scientist",
  MAINTENANCE_MANAGER: "Maintenance manager",
  DESIGNER: "Designer",
  OPERATIONS: "Operations",
  FUNCTIONAL_ADVISER: "Functional adviser",
  TECHNICAL_ADVISER: "Technical adviser",
  TECHNICAL_TESTER: "Technical tester",

  INTERNAL: "Internal",
  EXTERNAL: "External",

  administrate: "Admin",
  CREATE: "Create",
  DELETE: "Delete",
  UPDATE: "Update",
  action: "Action",
  audit: "Audit",
  auditNotFound: "No audits found",
  auditNr: "Audit #",
  audits: "Audits",
  close: "Close",
  emptyTable: "No",
  id: "Id",
  searchId: "Search by id",
  lastChanges: "Last changes",
  prevButton: "Previous",
  nextButton: "Next",
  rows: "Rows",
  table: "Table name",
  time: "Time",
  user: "User",
  version: "Version",
  view: "View",
  settings: "Settings",
  abort: "Abort",
  save: "Save",
  pageNotFound: "Oops 404! Couldn't find that page",
  teamNotFound: "Could not find the team",
  producatAreaNotFound: "Could not find the area",
  linkToAllTeamsText: "Go to all teams",
  linkToAllProductAreasText: "Go to all areas",
};
