CREATE TABLE IF NOT EXISTS AUDIT_VERSION
(
    AUDIT_ID     UUID       PRIMARY KEY,
    ACTION       TEXT       NOT NULL,
    TABLE_NAME   TEXT       NOT NULL,
    TABLE_ID     TEXT       NOT NULL,
    USER_ID TEXT NOT            NULL,
    TIME         TIMESTAMP  NOT NULL,
    DATA         JSONB      NOT NULL
);

CREATE INDEX IF NOT EXISTS AUDIT_VERSION_TIME ON AUDIT_VERSION (TIME DESC);
CREATE INDEX IF NOT EXISTS AUDIT_VERSION_TABLE_ID ON AUDIT_VERSION (TABLE_ID);