apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: team-catalog-frackend-alerts
  namespace: org
  labels:
    team: org
spec:
  groups:
    - name: team-catalog-frackend_down
      rules:
        - alert: team-catalog-frackend applikasjon nede
          expr: up{app="team-catalog-frackend", job="kubernetes-pods"} == 0
          for: 3m
          annotations:
            action: "`kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }} -c {{ $labels.app }}` for logger"
            summary: "{{ $labels.app }} er nede"
          labels:
            namespace: org
            severity: critical
    - name: team-catalog-frackend_high_failrate
      rules:
        - alert: team-catalog-frackend høy feilrate i logger
          expr: (sum(loki:service:loglevel:count1m{service_name="team-catalog-frackend", detected_level="error"}) / sum(loki:service:loglevel:count1m{service_name="team-catalog-frackend"})) > 0.05
          for: 3m
          annotations:
            summary: "{{ $labels.service_name }} har {{ $value | humanizePercentage }} feilmeldinger i loggene i løpet av de siste 3 minuttene."
          labels:
            namespace: org
            severity: warning