apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{name}}
  namespace: org
  labels:
    team: org
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{azure.application.tenant}}
      replyURLs:
      {{#each azure.application.replyURLs as |url|}}
         - {{url}}
      {{/each}}
  accessPolicy:
    outbound:
      external:
        {{#each accessPolicy.outbound.external}}
          - host: {{this.host}}
        {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: internal/prometheus
  env:
  {{#each env}}
      - name: {{this.name}}
        value: {{this.value}}
  {{/each}}
