apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: team-catalog-frackend
  namespace: org
  labels:
    team: org
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      singlePageApplication: true
      tenant: trygdeetaten.no
      replyURLs:
        - http://localhost:8080/oauth2/callback
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - "/frackend/*"
  accessPolicy:
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
          cluster: dev-gcp
        - application: nom-azure
          namespace: org
          cluster: dev-gcp
      external:
        - host: teamorg-unleash-api.nav.cloud.nais.io
  ingresses:
    - https://teamkatalog.ekstern.dev.nav.no
    - https://teamkatalog-beta.ekstern.dev.nav.no
    - https://teamkatalogen.ekstern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: NODE_ENV
      value: "production"
    - name: EXPRESS_HOST
      value: "::"
    - name: EXPRESS_PORT
      value: "8080"
    - name: TEAM_CATALOG_API_URL
      value: http://team-catalog-backend
    - name: TEAM_CATALOG_SCOPE
      value: api://dev-gcp.org.team-catalog-backend/.default
    - name: NOM_API_URL
      value: http://nom-api.nom.svc.cluster.local
    - name: NOM_API_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
    - name: NOM_AZURE_URL
      value: http://nom-azure.org.svc.cluster.local
    - name: NOM_AZURE_SCOPE
      value: api://dev-gcp.org.nom-azure/.default
    - name: DEFAULT_BASE_URL
      value: https://teamkatalog.ekstern.dev.nav.no
  envFrom:
    - secret: team-catalog-frackend-unleash-api-token