name: Backend

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - '.github/workflows/team-backend.yml'
      - 'apps/backend/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/teambackend:${{ github.sha }}

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn compile
      - name: Test and Package
        run: mvn package

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker container
        uses: docker/build-push-action@v3
        with:
          context: apps/backend
          push: true
          tags: ${{ env.IMAGE }}
          build-args: JAR_PATH=target/app.jar

  deploy-preprod:
    name: Backend - deploy Dev FSS
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-dev-fss-vars.yaml
          
  deploy-prod:
    name: Backend - deploy Prod FSS
    needs: deploy-preprod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-prod-fss-vars.yaml

