name: "verify: backend"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'apps/backend/**'
      - '.github/workflows/verify-backend.yaml'
      - 'apps/backend/pom.xml'
  workflow_dispatch:

jobs:
  verify:
    name: Verify backend compiles and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Run tests
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean test --also-make --batch-mode
