name: "verify: backend"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'apps/backend/**'
      - '.github/workflows/verify-backend.yaml'
      - 'apps/backend/pom.xml'
  workflow_dispatch:

jobs:
  verify:
    name: Verify backend compiles and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run tests
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean test --also-make --batch-mode
