name: "verify: frontend"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'apps/frontend/**'
      - '.github/*/verify-frontend.yaml'

jobs:
  verify:
    name: Verify there are no lint or typescript errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'npm'
          cache-dependency-path: apps/frontend
      - name: Install dependencies
        working-directory: apps/frontend
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run ESLint
        working-directory: apps/frontend
        run: npm run lint

      - name: Run Stylelint
        working-directory: apps/frontend
        run: npm run stylelint

      - name: Check for typescript errors
        working-directory: apps/frontend
        run: npm run check-types
